// Fallback product data untuk ketika JSON file tidak bisa diakses
const fallbackProductData = [
    {
        "id": 1,
        "name": "Pearl Whisper Flats",
        "price": 329000,
        "image": "Images/product1.jpg.jpg",
        "category": "Ballet flats",
        "description": " Ballet flats putih dengan aksen pita dan charm mutiara & hati metalik. Manis, minimalis, timeless.",
        "longDescription": "menghadirkan keanggunan yang sederhana dalam balutan warna putih bersih. Dengan ornamen mutiara dan pita halus di bagian depan, sepatu ini sempurna untuk penampilan sehari-hari yang stylish namun tetap nyaman. Sol datar yang fleksibel membuatnya cocok untuk aktivitas harian tanpa mengurangi gaya",
        "features": ["Material kulit sintetis premium", "Sol karet anti-slip", "Lapisan dalam yang lembut", "Charm mutiara dan hati metalik", "Desain timeless yang serbaguna"],
        "sizes": ["36", "37", "38", "39", "40", "41"],
        "colors": ["White Pearl"],
        "stock": 50,
        "rating": 4.8,
        "reviews": 300,
        "isNew": false,
        "isFeatured": true
    },
    {
        "id": 2,
        "name": "Blush Charm Flats",
        "price": 349000,
        "image": "Images/product2.jpg.png",
        "category": "Ballet flats",
        "description": "Ballet Flats pink satin dengan crisscross strap dan detail beads metalik. Desain feminin yang lembut.",
        "longDescription":"Blush Charm Flats memberikan sentuhan feminim dan lembut dalam warna pink pastel. Detail mutiara pada pita depan menambah kesan manis dan elegan, cocok dipadupadankan dengan berbagai outfit casual maupun semi formal untuk tampilan yang segar dan chic.",
        "features": ["Bahan kulit asli berkualitas tinggi", "Teknologi cushion comfort", "Sol anti-slip yang tahan lama", "Desain minimalis dan elegan", "Mudah dibersihkan dan dirawat"],
        "sizes": ["36", "37", "38", "39", "40", "41"],
        "colors": ["Soft Pink"],
        "stock": 60,
        "rating": 4.8,
        "reviews": 350, 
        "isNew": false,
        "isFeatured": true
        
    },
    {
        "id": 3,
        "name": "Sky Pearl Flats",
        "price": 379000,
        "image": "Images/product3.jpg.png",
        "category": "Ballet Flats",
        "description": "Ballets biru pastel dengan aksen pita dan charm mutiara, menghadirkan nuansa fresh, elegan, & anggun.",
        "longDescription": "Sky Grace Flats memadukan kenyamanan dengan keindahan berbalut warna biru pastel. Ornamen mutiara yang terpasang rapi pada tali depan memberikan aksen unik dan subtle. Sepatu ini cocok untuk Anda yang ingin tampil beda namun tetap simple dan elegan.",
        "features": ["Tinggi hak 7cm yang nyaman", "Material suede premium", "Bantalan kaki yang empuk", "Desain pointed toe yang elegan", "Tali ankle strap yang adjustable"],
        "sizes": ["36", "37", "38", "39", "40", "41"],
        "colors": ["Soft Blue"],
        "stock": 40,
        "rating": 4.8,
        "reviews": 390,
        "isNew": false,
        "isFeatured": true
    },
    {
        "id": 4,
        "name": "Emerald Satin ",
        "price": 425000,
        "image": "Images/product4.jpg.png",
        "category": "New Arrivals",
        "description": "Flat hijau satin dengan strap silang dan detail manik. Chic dan nyaman. ",
        "longDescription": "Emerald Satin Ballet menawarkan penampilan mewah dengan sentuhan bahan satin warna hijau emerald yang memukau. Tali silang pada bagian atas menambah kestabilan sekaligus mempercantik desain klasik ini, sempurna untuk acara spesial maupun santai",
        "features": ["Material mesh breathable", "Sistem ventilasi yang baik", "Sol EVA yang ringan", "Memory foam insole", "Desain slip-on yang praktis"],
        "sizes": ["36", "37", "38", "39", "40", "41"],
        "colors": ["Emerald"],
        "stock": 50,
        "rating": 4.8,
        "reviews": 200,
        "isNew": true,
        "isFeatured": false
    },
    {
        "id": 5,
        "name": "Golden Shine Ballet",
        "price": 440000,
        "image": "Images/product5 (2).png",
        "category": "New Arrivals",
        "description": "Flat emas metalik dengan strap silang dan bow. Glamor yang tetap wearable.",
        "longDescription": "Golden Shine Ballet memikat dengan kilau lembut satin berwana emas champagne. Dilengkapi tali silang dan pita klasik di depan, sepatu ini jadi pilihan utama untuk tampil glamour namun tetap nyaman sepanjang hari. ",
        "features": ["Kulit asli dengan finishing premium", "Hardware emas 18k gold plated", "Insole kulit yang lembut", "Sol karet berkualitas tinggi", "Detail stitching hand-crafted"],
        "sizes": ["36", "37", "38", "39", "40", "41"],
        "colors": ["Gold"],
        "stock": 60,
        "rating": 4.9,
        "reviews": 250,
        "isNew": true,
        "isFeatured":false
    },
    {
        "id": 6,
        "name": "Rose Gold satin Flats",
        "price": 475000,
        "image": "Images/product6.jpg.png",
        "category": "New Arrivals",
        "description": "Flat pink glossy dengan strap dan aksen mutiara. Manis dan sophisticated.",
        "longDescription": "Rose Gold Satin Flats menyuguhkan nuansa hangat dari warna dusty rose yang elegan dan manis. Dengan bahan satin berkualitas dan tali silang yang menambah gaya, sepatu ini sangat cocok untuk melengkapi penampilan feminin Anda.",
        "features": ["Aksen rose gold premium", "Material satin yang lembut", "Cushioned footbed", "Flexible rubber sole", "Elegant bow detail"],
        "sizes": ["36", "37", "38", "39", "40", "41"],
        "colors": ["Rose Gold"],
        "stock": 50,
        "rating": 4.8,
        "reviews": 340,
        "isNew": true,
        "isFeatured": false
    },
    {
        "id": 7,
        "name": "Ivory Knit",
        "price": 395000,
        "image": "Images/product7.jpg (2).png",
        "category": "New Arrivals",
        "description": "Mary Jane woven cream dengan tekstur anyaman. Natural dan stylish.",
        "longDescription": "Ivory Knit merupakan perpaduan sempurna antara kenyamanan dan gaya. Bahan rajut yang breathable membuat sepatu ini ideal untuk cuaca hangat, sementara desain mary janes ala klasik menambahkan sentuhan vintage yang timeless.",
        "features": ["Teknologi cushioning terdepan", "Upper material premium synthetic", "Breathable mesh lining", "Rubber outsole anti-slip", "Modern chunky design"],
        "sizes": ["36", "37", "38", "39", "40", "41"],
        "colors": ["Ivory"],
        "stock": 40,
        "rating": 4.8,
        "reviews": 270,
        "isNew": true,
        "isFeatured": false
    },
    {
        "id": 8,
        "name": "Satin Brown Flats",
        "price": 455000,
        "image": "Images/product8.jpg.png",
        "category": "High Heels",
        "description": "Sepatu coklat tua dengan bahan kulit halus dan simple",
        "longDescription": "Chocolate Classic mengedepankan kesan klasik dan sederhana dengan kulit coklat premium dan tali pengait yang praktis. Sepatu ini cocok dipakai sehari-hari maupun untuk acara semi formal.",
        "features": ["Padded insole untuk comfort", "Classic pointed toe", "Professional finish"],
        "sizes": ["36", "37", "38", "39", "40", "41"],
        "colors": ["chocolate brown"],
        "stock": 50,
        "rating": 4.8,
        "reviews": 300,
        "ishigh heels": true,
        "isFeatured": false
    },
    {
        "id": 9,
        "name": "Blush Pearl Flat",
        "price": 465000,
        "image": "Images/product9.jpg.jpeg",
        "category": "Wedges",
        "description": "Flat suede beige dengan strap mutiara besar. Statement piece yang tetap elegan.",
        "longDescription": "Nude Pearl Strap Flats hadir dengan desain minimalis modern yang diperkaya aksen mutiara besar sebagai pemanis pada tali strap. Warna nude glossy membuatnya versatile, cocok dipadukan dengan berbagai pilihan outfit.",
        "features": ["Platform wedge 3cm", "Ergonomic footbed", "Adjustable ankle strap", "Non-slip rubber sole", "Breathable lining"],
        "sizes": ["36", "37", "38", "39", "40", "41"],
        "colors": ["soft blush pink"],
        "stock": 60,
        "rating": 4.8,
        "reviews": 400,
        "isNew": true,
        "isFeatured": false
       
    },
    {
        "id": 10,
        "name": "Nude Glossy Flats",
        "price": 475000,
        "image": "Images/product10.jpg.png",
        "category": "Sport Shoes",
        "description": "Flat glossy cream dengan strap mutiara besar. Classy dan cocok untuk acara spesial.",
        "longDescription": "Classic Beige pilihan ideal untuk Anda yang menyukai desain sederhana namun berkelas. Dengan bahan glossy dan tali kecil bertali buckle, sepatu ini memberi kesan elegan tanpa berlebihan.", 
        "features": ["Advanced cushioning technology", "Moisture-wicking material", "Lightweight EVA midsole", "Fashionable color combination", "Durable rubber outsole"],
        "sizes": ["36", "37", "38", "39", "40", "41"],
        "colors": ["beige nude"],
        "stock": 70,
        "rating": 4.8,
        "reviews": 250,
        "isNew": false,
        "isFeatured": true
    },
    {
        "id": 11,
        "name": "Pearl Elegance Flats",
        "price": 490000,
        "image": "Images/product12.jpg.png",
        "category": "Ballet Flats",
        "description": " Flats suede beige dengan strap mutiara sebagai pemanis.",
        "longDescription": "Pearl Elegance Flats menggabungkan keanggunan mutiara dengan kenyamanan suede berwarna beige. Strap mutiara menambah sentuhan glamor yang sangat pas untuk acara formal maupun kasual.",
        "features": ["Premium leather construction", "Modern comfort technology", "Vintage-inspired design", "Durable leather sole"],
        "sizes": ["36", "37", "38", "39", "40", "41"],
        "colors": ["taupe suede"],
        "stock": 40,
        "rating": 4.8,
        "reviews": 400,
        "isNew": false,
        "isFeatured":true
    },
    {
        "id": 12,
        "name": "Ivory Pearl Grace",
        "price": 480000,
        "image": "Images/product11.jpg.png",
        "category": "Ballet Flats",
        "description": "Flats ivory glossy dengan strap mutiara yang elegan.",
        "longDescription": "Ivory Pearl Grace menonjolkan keindahan pada detail strap mutiara yang membingkai kaki dengan anggun. Bahan glossy berwarna ivory menambah kesan mewah dan minimalis yang cocok untuk berbagai kesempatan. ",
        "features": ["Soft leather straps", "Comfortable padded sole", "Bohemian decorative elements", "Adjustable buckle closure", "Lightweight construction"],
        "sizes": ["36", "37", "38", "39", "40", "41"],
        "colors": ["Ivory"],
        "stock": 30,
        "rating": 4.8,
        "reviews": 230,
        "isNew": false,
        "isFeatured": true
    },
    {
        "id": 13,
        "name": "Ruby Charm Heels",
        "price": 490000,
        "image": "Images/product14.jpg.png",
        "category": "High Heels",
        "description": "Ruby Charm merah glossy dengan heels pendek dan aksen bunga di buckle.",
        "longDescription": "Ruby Charm memadukan warna merah glossy memikat dengan detail bunga di buckle yang unik, menciptakan kesan playful namun tetap elegant.",
        "features": ["Premium satin material", "Swarovski crystal details", "6cm stiletto heel", "Cushioned insole", "Elegant evening design"],
        "sizes": ["36", "37", "38", "39", "40", "41"],
        "colors": ["Red glossy"],
        "stock": 50,
        "rating": 4.9,
        "reviews": 320,
        "ishigh heels": true,
        "isFeatured": false
    },
    {
        "id": 14,
        "name": "Cocoa Classic Flats",
        "price": 485000,
        "image": "Images/product13.jpg.png",
        "category": "New Arrivals",
        "description": " Soft Brown Flats berbahan velvet yang hangat dan klasik dengan strap buckle.",
        "longDescription": "Velvet Brown menghadirkan suasana hangat dan nyaman lewat bahan velvet yang halus dengan warna coklat tua elegan. Strap buckle menambah kesan klasik yang cocok untuk tampilan sehari-hari yang stylish.",
        "features": ["Premium leather construction", "Traditional Oxford lacing", "Modern comfort technology", "Vintage-inspired design", "Durable leather sole"],
        "sizes": ["36", "37", "38", "39", "40", "41"],
        "colors": ["dark brown"],
        "stock": 60,
        "rating": 4.8,
        "reviews": 313,
        "isNew": true,
        "isFeatured": false
    },
    {
        "id": 15,
        "name": "Tweed Chic Flats",
        "price": 475000,
        "image": "Images/product15.jpg.png",
        "category": "Ballet Flats",
        "description": "Flats berbahan tweed putih dengan buckle glamor.",
        "longDescription": "Elegant Tweed menghadirkan gaya unik dengan bahan tweed putih soft yang klasik. Dilengkapi buckle berhiaskan kristal, sepatu ini memberikan kesan mewah tanpa berlebihan, cocok untuk acara formal maupun casual smart.",
        "features": ["Soft blush pink leather", "Cushioned footbed", "Flexible rubber sole", "Elegant bow detail", "Comfortable all-day wear"],
        "sizes": ["36", "37", "38", "39", "40", "41"],
        "colors": ["ivory tweed"],
        "stock": 50,
        "rating": 4.8,
        "reviews": 270,
        "isNew": true,
        "isFeatured": false
    }
];

// Ekspos data ke window object agar bisa diakses oleh ProductManager
window.fallbackProductData = fallbackProductData;
